import { useEffect, useState } from "react";
import { useParams } from "react-router-dom";
import { Factory, MapPin, MessageCircle, Phone, Package } from "lucide-react";
import BackButton from "@/components/BackButton";
import { supabase } from "@/integrations/supabase/client";

export default function FactoryDetails() {
  const { id } = useParams(); const [factory, setFactory] = useState<any>(null); const [products, setProducts] = useState<any[]>([]);
  useEffect(() => { void (async () => { const [{ data: f }, { data: p }] = await Promise.all([(supabase.from("factories") as any).select("*").eq("id", id).eq("status", "active").maybeSingle(), (supabase.from("factory_products") as any).select("*").eq("factory_id", id).eq("status", "active").eq("in_stock", true)]); setFactory(f); setProducts(p || []); })(); }, [id]);
  if (!factory) return <main className="container mx-auto px-4 py-10">Chargement…</main>;
  const whatsapp = (factory.whatsapp || factory.telephone || "").replace(/\D/g, "");
  return <main className="container mx-auto px-4 py-10"><BackButton /><section className="mt-7 rounded-3xl border border-border bg-card p-6 md:p-10"><div className="flex flex-col gap-6 md:flex-row md:items-center"><div className="flex h-32 w-32 items-center justify-center rounded-2xl bg-muted p-4">{factory.logo ? <img src={factory.logo} alt={factory.company_name} className="h-full w-full object-contain" /> : <Factory className="h-12 w-12" />}</div><div><h1 className="text-3xl font-bold">{factory.company_name}</h1><p className="mt-2 flex items-center gap-2 text-muted-foreground"><MapPin className="h-4 w-4" />{[factory.city, factory.country].filter(Boolean).join(", ")}</p><p className="mt-4 text-muted-foreground">{factory.description}</p><div className="mt-5 flex gap-3">{factory.telephone && <a href={`tel:${factory.telephone}`} className="inline-flex items-center gap-2 text-primary"><Phone className="h-4 w-4" />Appeler</a>}{whatsapp && <a href={`https://wa.me/${whatsapp}`} className="inline-flex items-center gap-2 text-primary"><MessageCircle className="h-4 w-4" />WhatsApp</a>}</div></div></div></section><section className="mt-10"><h2 className="text-2xl font-bold">Produits de l’usine</h2><div className="mt-5 grid gap-5 sm:grid-cols-2 lg:grid-cols-3">{products.map((product) => <article key={product.id} className="overflow-hidden rounded-xl border border-border bg-card">{product.image ? <img src={product.image} alt={product.name} className="h-48 w-full object-contain bg-muted" /> : <div className="flex h-48 items-center justify-center bg-muted"><Package /></div>}<div className="p-4"><p className="text-sm text-primary">{product.category}</p><h3 className="mt-1 font-bold">{product.name}</h3><p className="mt-2 text-sm text-muted-foreground">{product.description}</p><p className="mt-3 font-bold text-primary">{Number(product.price).toLocaleString("fr-FR")} FCFA</p></div></article>)}</div>{products.length === 0 && <p className="mt-5 text-muted-foreground">Aucun produit disponible pour le moment.</p>}</section></main>;
}
