CREATE TABLE IF NOT EXISTS public.restaurant_outlets (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  organization_id BIGINT NOT NULL REFERENCES public.organizations(id) ON DELETE CASCADE,
  restaurant_id UUID NOT NULL REFERENCES public.restaurant_partners(id) ON DELETE CASCADE,
  name TEXT NOT NULL,
  neighborhood TEXT,
  address TEXT,
  telephone TEXT,
  manager_user_id UUID REFERENCES public.profiles(id) ON DELETE SET NULL,
  is_primary BOOLEAN NOT NULL DEFAULT FALSE,
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  created_by UUID REFERENCES public.profiles(id) ON DELETE SET NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS restaurant_outlets_one_primary ON public.restaurant_outlets(organization_id) WHERE is_primary;
CREATE UNIQUE INDEX IF NOT EXISTS restaurant_outlets_org_name ON public.restaurant_outlets(organization_id, LOWER(name));
CREATE INDEX IF NOT EXISTS restaurant_outlets_restaurant_idx ON public.restaurant_outlets(restaurant_id, is_active);

ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS restaurant_outlet_id BIGINT REFERENCES public.restaurant_outlets(id) ON DELETE SET NULL;
ALTER TABLE public.orders ADD COLUMN IF NOT EXISTS restaurant_outlet_id BIGINT REFERENCES public.restaurant_outlets(id) ON DELETE SET NULL;
ALTER TABLE public.warehouses ADD COLUMN IF NOT EXISTS restaurant_outlet_id BIGINT REFERENCES public.restaurant_outlets(id) ON DELETE SET NULL;
ALTER TABLE public.organization_cash_sessions ADD COLUMN IF NOT EXISTS restaurant_outlet_id BIGINT REFERENCES public.restaurant_outlets(id) ON DELETE RESTRICT;
ALTER TABLE public.organization_financial_entries ADD COLUMN IF NOT EXISTS restaurant_outlet_id BIGINT REFERENCES public.restaurant_outlets(id) ON DELETE SET NULL;
ALTER TABLE public.organization_activity_events ADD COLUMN IF NOT EXISTS restaurant_outlet_id BIGINT REFERENCES public.restaurant_outlets(id) ON DELETE SET NULL;

INSERT INTO public.restaurant_outlets (organization_id, restaurant_id, name, neighborhood, address, telephone, is_primary)
SELECT rp.organization_id, rp.id, COALESCE(rp.name, 'Point de vente principal'), rp.location, rp.location, rp.telephone, TRUE
FROM public.restaurant_partners rp
WHERE rp.organization_id IS NOT NULL
AND NOT EXISTS (SELECT 1 FROM public.restaurant_outlets ro WHERE ro.organization_id = rp.organization_id);

UPDATE public.orders o SET restaurant_outlet_id = ro.id FROM public.restaurant_outlets ro WHERE o.restaurant_id = ro.restaurant_id AND ro.is_primary AND o.restaurant_outlet_id IS NULL;
UPDATE public.organization_cash_sessions s SET restaurant_outlet_id = ro.id FROM public.restaurant_outlets ro WHERE s.organization_id = ro.organization_id AND ro.is_primary AND s.restaurant_outlet_id IS NULL;
UPDATE public.organization_financial_entries f SET restaurant_outlet_id = ro.id FROM public.restaurant_outlets ro WHERE f.organization_id = ro.organization_id AND ro.is_primary AND f.restaurant_outlet_id IS NULL;
UPDATE public.organization_activity_events e SET restaurant_outlet_id = ro.id FROM public.restaurant_outlets ro WHERE e.organization_id = ro.organization_id AND ro.is_primary AND e.restaurant_outlet_id IS NULL;

DROP INDEX IF EXISTS public.organization_one_open_cash_session;
CREATE UNIQUE INDEX IF NOT EXISTS organization_outlet_one_open_cash_session ON public.organization_cash_sessions(organization_id, restaurant_outlet_id) WHERE status = 'open';
CREATE INDEX IF NOT EXISTS profiles_restaurant_outlet_idx ON public.profiles(restaurant_outlet_id);
CREATE INDEX IF NOT EXISTS orders_restaurant_outlet_created_idx ON public.orders(restaurant_outlet_id, created_at DESC);
CREATE INDEX IF NOT EXISTS organization_cash_outlet_idx ON public.organization_cash_sessions(restaurant_outlet_id, opened_at DESC);
CREATE INDEX IF NOT EXISTS organization_finance_outlet_idx ON public.organization_financial_entries(restaurant_outlet_id, occurred_at DESC);

ALTER TABLE public.restaurant_outlets ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public.restaurant_outlets FROM anon, authenticated;
GRANT ALL ON TABLE public.restaurant_outlets TO service_role;
GRANT USAGE, SELECT ON SEQUENCE public.restaurant_outlets_id_seq TO service_role;
