-- =========================================================
-- Flotte de camions par organisation (onglet Logistique du
-- dashboard PDG partenaire) : meme schema d'acces que
-- warehouses/organization_products, tout passe par l'edge
-- function organization-portal.
-- =========================================================

CREATE TABLE IF NOT EXISTS public.trucks (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  organization_id BIGINT NOT NULL REFERENCES public.organizations(id) ON DELETE CASCADE,

  -- Informations generales
  title TEXT NOT NULL,
  vehicle_type TEXT,
  brand TEXT,
  model TEXT,
  year_built INTEGER,
  registration_number TEXT,
  registration_country TEXT,
  registration_city TEXT,
  condition TEXT,
  availability_status TEXT NOT NULL DEFAULT 'available',

  -- Caracteristiques techniques
  axle_count INTEGER,
  wheel_count INTEGER,
  fuel_type TEXT,
  transmission_type TEXT,
  engine_power TEXT,
  mileage_km NUMERIC,
  payload_tons NUMERIC,
  max_weight_kg NUMERIC,
  length_m NUMERIC,
  width_m NUMERIC,
  height_m NUMERIC,
  loading_volume_m3 NUMERIC,
  suspension_type TEXT,
  has_air_conditioning BOOLEAN NOT NULL DEFAULT false,
  has_gps BOOLEAN NOT NULL DEFAULT false,
  tire_condition TEXT,
  last_service_date DATE,
  next_inspection_date DATE,

  -- Conditions de location
  rental_with_driver BOOLEAN,
  daily_rate NUMERIC,
  weekly_rate NUMERIC,
  monthly_rate NUMERIC,
  km_rate NUMERIC,
  security_deposit NUMERIC,
  available_from DATE,
  available_until DATE,

  -- Documents requis (presents ou non)
  has_registration_certificate BOOLEAN NOT NULL DEFAULT false,
  has_insurance BOOLEAN NOT NULL DEFAULT false,
  has_inspection_certificate BOOLEAN NOT NULL DEFAULT false,
  has_tax_sticker BOOLEAN NOT NULL DEFAULT false,
  has_driver_license BOOLEAN NOT NULL DEFAULT false,
  has_transport_authorization BOOLEAN NOT NULL DEFAULT false,
  has_customs_document BOOLEAN NOT NULL DEFAULT false,

  image_urls TEXT[] NOT NULL DEFAULT '{}',
  actif BOOLEAN NOT NULL DEFAULT true,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
  updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()
);

ALTER TABLE public.trucks ENABLE ROW LEVEL SECURITY;

-- Pas de policy publique : tout passe par l'edge function organization-portal
-- (service role), qui applique les regles d'appartenance a l'organisation
-- et les permissions CEO/manager pour l'ecriture.
DROP POLICY IF EXISTS "Bloquer l'acces public direct" ON public.trucks;
CREATE POLICY "Bloquer l'acces public direct" ON public.trucks FOR ALL TO anon, authenticated USING (false) WITH CHECK (false);
