-- =========================================================
-- Dashboard PDG partenaire : magasins/entrepots, catalogue
-- produits independant par organisation, stock par magasin,
-- et suivi de performance des employes.
-- =========================================================

CREATE TABLE IF NOT EXISTS public.warehouses (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  organization_id BIGINT NOT NULL REFERENCES public.organizations(id) ON DELETE CASCADE,
  name TEXT NOT NULL,
  address TEXT,
  latitude DOUBLE PRECISION,
  longitude DOUBLE PRECISION,
  actif BOOLEAN NOT NULL DEFAULT true,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
  updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.organization_products (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  organization_id BIGINT NOT NULL REFERENCES public.organizations(id) ON DELETE CASCADE,
  name TEXT NOT NULL,
  description TEXT,
  category TEXT,
  price NUMERIC NOT NULL DEFAULT 0 CHECK (price >= 0),
  unit TEXT,
  image TEXT,
  actif BOOLEAN NOT NULL DEFAULT true,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
  updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.warehouse_stock (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  warehouse_id BIGINT NOT NULL REFERENCES public.warehouses(id) ON DELETE CASCADE,
  organization_product_id BIGINT NOT NULL REFERENCES public.organization_products(id) ON DELETE CASCADE,
  quantity NUMERIC NOT NULL DEFAULT 0 CHECK (quantity >= 0),
  updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
  UNIQUE (warehouse_id, organization_product_id)
);

-- Compteurs de performance mis a jour par les processus metier (commandes,
-- validations, etc.) ; consultes en lecture par le dashboard PDG/employe.
CREATE TABLE IF NOT EXISTS public.employee_performance (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  organization_id BIGINT NOT NULL REFERENCES public.organizations(id) ON DELETE CASCADE,
  period_month DATE NOT NULL, -- toujours le 1er jour du mois concerne
  sales_amount NUMERIC NOT NULL DEFAULT 0,
  orders_handled INTEGER NOT NULL DEFAULT 0,
  partners_recruited INTEGER NOT NULL DEFAULT 0,
  last_activity_at TIMESTAMP WITH TIME ZONE,
  updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
  UNIQUE (user_id, organization_id, period_month)
);

ALTER TABLE public.warehouses ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.organization_products ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.warehouse_stock ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.employee_performance ENABLE ROW LEVEL SECURITY;

-- Pas de policy publique : tout passe par l'edge function organization-portal
-- (service role), qui applique les regles d'appartenance a l'organisation.
DROP POLICY IF EXISTS "Bloquer l'acces public direct" ON public.warehouses;
CREATE POLICY "Bloquer l'acces public direct" ON public.warehouses FOR ALL TO anon, authenticated USING (false) WITH CHECK (false);

DROP POLICY IF EXISTS "Bloquer l'acces public direct" ON public.organization_products;
CREATE POLICY "Bloquer l'acces public direct" ON public.organization_products FOR ALL TO anon, authenticated USING (false) WITH CHECK (false);

DROP POLICY IF EXISTS "Bloquer l'acces public direct" ON public.warehouse_stock;
CREATE POLICY "Bloquer l'acces public direct" ON public.warehouse_stock FOR ALL TO anon, authenticated USING (false) WITH CHECK (false);

DROP POLICY IF EXISTS "Bloquer l'acces public direct" ON public.employee_performance;
CREATE POLICY "Bloquer l'acces public direct" ON public.employee_performance FOR ALL TO anon, authenticated USING (false) WITH CHECK (false);
