CREATE TABLE IF NOT EXISTS public.organization_cash_sessions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  organization_id BIGINT NOT NULL REFERENCES public.organizations(id) ON DELETE CASCADE,
  opened_by UUID NOT NULL REFERENCES public.profiles(id),
  closed_by UUID REFERENCES public.profiles(id),
  opened_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  closed_at TIMESTAMPTZ,
  opening_balance NUMERIC(14,2) NOT NULL DEFAULT 0 CHECK (opening_balance >= 0),
  expected_balance NUMERIC(14,2),
  closing_balance NUMERIC(14,2),
  variance NUMERIC(14,2),
  status TEXT NOT NULL DEFAULT 'open' CHECK (status IN ('open', 'closed')),
  notes TEXT
);

CREATE UNIQUE INDEX IF NOT EXISTS organization_one_open_cash_session
ON public.organization_cash_sessions (organization_id)
WHERE status = 'open';

CREATE INDEX IF NOT EXISTS organization_cash_sessions_org_opened_idx
ON public.organization_cash_sessions (organization_id, opened_at DESC);

CREATE TABLE IF NOT EXISTS public.organization_financial_entries (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  organization_id BIGINT NOT NULL REFERENCES public.organizations(id) ON DELETE CASCADE,
  entry_type TEXT NOT NULL CHECK (entry_type IN ('income', 'expense')),
  category TEXT NOT NULL,
  amount NUMERIC(14,2) NOT NULL CHECK (amount > 0),
  payment_method TEXT,
  description TEXT,
  order_id UUID REFERENCES public.orders(id) ON DELETE SET NULL,
  cash_session_id BIGINT REFERENCES public.organization_cash_sessions(id) ON DELETE SET NULL,
  recorded_by UUID NOT NULL REFERENCES public.profiles(id),
  occurred_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX IF NOT EXISTS organization_financial_entries_order_income_unique
ON public.organization_financial_entries (organization_id, order_id)
WHERE entry_type = 'income' AND order_id IS NOT NULL;

CREATE INDEX IF NOT EXISTS organization_financial_entries_org_date_idx
ON public.organization_financial_entries (organization_id, occurred_at DESC);

CREATE TABLE IF NOT EXISTS public.organization_activity_events (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  organization_id BIGINT NOT NULL REFERENCES public.organizations(id) ON DELETE CASCADE,
  actor_user_id UUID REFERENCES public.profiles(id) ON DELETE SET NULL,
  event_type TEXT NOT NULL,
  entity_type TEXT,
  entity_id TEXT,
  details JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS organization_activity_events_org_date_idx
ON public.organization_activity_events (organization_id, created_at DESC);

ALTER TABLE public.organization_cash_sessions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.organization_financial_entries ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.organization_activity_events ENABLE ROW LEVEL SECURITY;

REVOKE ALL ON TABLE public.organization_cash_sessions FROM anon, authenticated;
REVOKE ALL ON TABLE public.organization_financial_entries FROM anon, authenticated;
REVOKE ALL ON TABLE public.organization_activity_events FROM anon, authenticated;

GRANT ALL ON TABLE public.organization_cash_sessions TO service_role;
GRANT ALL ON TABLE public.organization_financial_entries TO service_role;
GRANT ALL ON TABLE public.organization_activity_events TO service_role;
