-- =========================================================
-- Migration de rattrapage : ces tables existent deja en
-- production (creees a la main via le dashboard Supabase)
-- mais n'avaient jamais ete versionnees. Tout est en
-- "IF NOT EXISTS" : aucun effet sur la base actuelle, cela
-- sert a ce qu'un nouvel environnement (dev, staging, autre
-- machine) puisse recreer exactement le meme schema.
-- =========================================================

-- Valeurs reelles observees en production pour l'enum user_role
DO $$
BEGIN
  ALTER TYPE public.user_role ADD VALUE IF NOT EXISTS 'client';
  ALTER TYPE public.user_role ADD VALUE IF NOT EXISTS 'representant';
  ALTER TYPE public.user_role ADD VALUE IF NOT EXISTS 'commercial';
  ALTER TYPE public.user_role ADD VALUE IF NOT EXISTS 'agency';
  ALTER TYPE public.user_role ADD VALUE IF NOT EXISTS 'partner';
  ALTER TYPE public.user_role ADD VALUE IF NOT EXISTS 'transport_pdg';
  ALTER TYPE public.user_role ADD VALUE IF NOT EXISTS 'transport_station_manager';
  ALTER TYPE public.user_role ADD VALUE IF NOT EXISTS 'transport_courier_manager';
  ALTER TYPE public.user_role ADD VALUE IF NOT EXISTS 'transport_accountant';
  ALTER TYPE public.user_role ADD VALUE IF NOT EXISTS 'transport_driver';
  ALTER TYPE public.user_role ADD VALUE IF NOT EXISTS 'transport_agent';
  ALTER TYPE public.user_role ADD VALUE IF NOT EXISTS 'transport_cashier';
  ALTER TYPE public.user_role ADD VALUE IF NOT EXISTS 'transport_controller';
  ALTER TYPE public.user_role ADD VALUE IF NOT EXISTS 'transport_baggage_agent';
  ALTER TYPE public.user_role ADD VALUE IF NOT EXISTS 'transport_baggage_controller';
  ALTER TYPE public.user_role ADD VALUE IF NOT EXISTS 'transport_staff';
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

CREATE TABLE IF NOT EXISTS public.countries (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL UNIQUE,
  iso_code VARCHAR,
  phone_code VARCHAR,
  currency VARCHAR,
  currency_code VARCHAR,
  currency_symbol VARCHAR,
  is_active BOOLEAN DEFAULT true,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.organizations (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  organization_type TEXT NOT NULL,
  logo_url TEXT,
  country_id BIGINT REFERENCES public.countries(id),
  city_id BIGINT,
  commune_id BIGINT,
  email TEXT,
  telephone TEXT,
  whatsapp TEXT,
  address TEXT,
  actif BOOLEAN DEFAULT true,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
  created_by UUID REFERENCES auth.users(id),
  commercial_agent_id UUID REFERENCES auth.users(id),
  validation_status TEXT NOT NULL DEFAULT 'pending',
  validated_by UUID REFERENCES auth.users(id),
  validated_at TIMESTAMP WITH TIME ZONE
);

CREATE TABLE IF NOT EXISTS public.organization_roles (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  organization_id BIGINT NOT NULL REFERENCES public.organizations(id),
  name TEXT NOT NULL,
  code TEXT NOT NULL UNIQUE,
  description TEXT,
  actif BOOLEAN DEFAULT true,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
  hierarchy_level INTEGER NOT NULL DEFAULT 99,
  parent_role_id BIGINT REFERENCES public.organization_roles(id)
);

CREATE TABLE IF NOT EXISTS public.permissions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code TEXT NOT NULL UNIQUE,
  name TEXT NOT NULL,
  description TEXT,
  category TEXT,
  actif BOOLEAN NOT NULL DEFAULT true,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.role_permissions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  organization_role_id BIGINT NOT NULL REFERENCES public.organization_roles(id),
  permission_id BIGINT NOT NULL REFERENCES public.permissions(id),
  actif BOOLEAN NOT NULL DEFAULT true,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.access_scopes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES auth.users(id),
  organization_id BIGINT NOT NULL REFERENCES public.organizations(id),
  scope_type TEXT NOT NULL,
  scope_id BIGINT,
  actif BOOLEAN NOT NULL DEFAULT true,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
  country_id BIGINT REFERENCES public.countries(id)
);

CREATE TABLE IF NOT EXISTS public.user_management (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  manager_user_id UUID NOT NULL REFERENCES auth.users(id),
  managed_user_id UUID NOT NULL REFERENCES auth.users(id),
  organization_id BIGINT NOT NULL REFERENCES public.organizations(id),
  actif BOOLEAN NOT NULL DEFAULT true,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
  UNIQUE (manager_user_id),
  UNIQUE (managed_user_id),
  UNIQUE (organization_id)
);

-- Colonnes organisationnelles ajoutees sur profiles hors migrations
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS organization_id BIGINT REFERENCES public.organizations(id);
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS organization_role_id BIGINT REFERENCES public.organization_roles(id);
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS manager_user_id UUID REFERENCES auth.users(id);
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS country_id BIGINT REFERENCES public.countries(id);
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS is_active BOOLEAN NOT NULL DEFAULT true;

ALTER TABLE public.countries ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.organizations ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.organization_roles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.permissions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.role_permissions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.access_scopes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.user_management ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS admin_read_countries ON public.countries;
CREATE POLICY admin_read_countries ON public.countries FOR SELECT TO authenticated
  USING (EXISTS (SELECT 1 FROM public.user_roles WHERE user_roles.user_id = auth.uid() AND user_roles.role = 'admin'::text));

DROP POLICY IF EXISTS admin_read_organizations ON public.organizations;
CREATE POLICY admin_read_organizations ON public.organizations FOR SELECT TO authenticated
  USING (EXISTS (SELECT 1 FROM public.user_roles WHERE user_roles.user_id = auth.uid() AND user_roles.role = 'admin'::text));

DROP POLICY IF EXISTS admin_read_organization_roles ON public.organization_roles;
CREATE POLICY admin_read_organization_roles ON public.organization_roles FOR SELECT TO authenticated
  USING (EXISTS (SELECT 1 FROM public.user_roles WHERE user_roles.user_id = auth.uid() AND user_roles.role = 'admin'::text));
